// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bqtxvfalitkqzxgqdvhu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJxdHh2ZmFsaXRrcXp4Z3Fkdmh1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI4MTY3MjMsImV4cCI6MjA2ODM5MjcyM30.RhpNvETbW_R0hRLQqLvOgPj-VZUAzagQsIR7S3ERcrM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});